#Choose your import : Local or Remote

#Local Fastfile
import "../../../POC/Fastlane-Template/fastlane/Fastfile-Android"

#Remote Fastfile
# import_from_git(
#   url: "git@github.com:Zenika/Fastlane-Template.git", # The URL of the repository to import the Fastfile from.
#   branch: "main", # The branch to checkout on the repository.
#   path: "fastlane/Fastfile-Android", # The path of the Fastfile in the repository.
#   version: "0.0.5" # The version to checkout on the repository. Optimistic match operator can be used to select the latest version within constraints.
# )

platform :android do
  before_all do |lane|
    setup_project
  end

  desc "Init project variables"
  lane :setup_project do
    init_project(
      flavor: ENV["FLAVOR"],
      build_type: ENV["BUILD_TYPE"],
      task: ENV["TASK"]
    ) 
  end

  desc "Build"
  lane :build_android do
    bump_version_number_and_build_number(version: ENV["REGEX"], build_number:ENV["BUILD_NUMBER"])
    #display_badge_on_appIcon(badge: "alpha", dark:true, version:true) #badge: alpha or beta or no-badge, dark: true or false(light) 
    build
  end
end